# Generated by Django 2.0.7 on 2018-08-08 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20180808_0856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='phone',
        ),
    ]
