# Generated by Django 2.0.7 on 2018-08-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20180808_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=30)),
                ('day', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Date',
                'verbose_name_plural': 'Date',
            },
        ),
        migrations.AddField(
            model_name='userinformation',
            name='birth_date',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
    ]
