# Generated by Django 2.0.7 on 2018-08-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20180808_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='gender',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
