# Generated by Django 2.0.7 on 2018-08-09 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20180808_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='gender',
        ),
    ]
